### ISSUE TITLE
Remove Typing dependencie

### ISSUE THREAD

**Issue by SergioFloresG** [CyberSource/cybersource-rest-samples-python#45]
I am implementing the service and when I try to execute the following message appears.

```
[ERROR] AttributeError: type object 'Callable' has no attribute '_abc_registry'
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app.py", line 5, in <module>
    from linksys.core.apigateway.response import response
  File "/opt/python/lib/python3.7/site-packages/linsys/core/apigateway/response.py", line 3, in <module>
    from typing import Any
  File "/var/task/typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "/var/task/typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
```

Manually delete the typing.py file, installed from the library dependencies, and do not generate the error.

**Details**
Python 3.7
cybersource-rest-client-python===0.0.20

**Comment by SergioFloresG** [comment]
Added the dependency tree when installing the library

```
cybersource-rest-client-python==0.0.20
  - asn1crypto [required: Any, installed: 1.4.0]
  - bcrypt [required: Any, installed: 3.2.0]
    - cffi [required: >=1.1, installed: 1.14.2]
      - pycparser [required: Any, installed: 2.20]
    - six [required: >=1.4.1, installed: 1.15.0]
  - certifi [required: Any, installed: 2020.6.20]
  - cffi [required: Any, installed: 1.14.2]
    - pycparser [required: Any, installed: 2.20]
  - chardet [required: Any, installed: 3.0.4]
  - configparser [required: Any, installed: 5.0.0]
  - coverage [required: Any, installed: 5.3]
  - crypto [required: Any, installed: 1.4.1]
    - Naked [required: Any, installed: 0.1.31]
      - pyyaml [required: Any, installed: 5.3.1]
      - requests [required: Any, installed: 2.24.0]
        - certifi [required: >=2017.4.17, installed: 2020.6.20]
        - chardet [required: >=3.0.2,<4, installed: 3.0.4]
        - idna [required: >=2.5,<3, installed: 2.7]
        - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
    - shellescape [required: Any, installed: 3.8.1]
  - cryptography [required: Any, installed: 3.1]
    - cffi [required: >=1.8,!=1.11.3, installed: 1.14.2]
      - pycparser [required: Any, installed: 2.20]
    - six [required: >=1.4.1, installed: 1.15.0]
  - DateTime [required: Any, installed: 4.3]
    - pytz [required: Any, installed: 2020.1]
    - zope.interface [required: Any, installed: 5.1.0]
      - setuptools [required: Any, installed: 47.1.0]
  - enum34 [required: Any, installed: 1.1.10]
  - extras [required: Any, installed: 1.0.0]
  - fixtures [required: Any, installed: 3.0.0]
    - pbr [required: >=0.11, installed: 5.5.0]
    - six [required: Any, installed: 1.15.0]
    - testtools [required: >=0.9.22, installed: 2.4.0]
      - extras [required: >=1.0.0, installed: 1.0.0]
      - pbr [required: >=0.11, installed: 5.5.0]
      - python-mimeparse [required: Any, installed: 1.6.0]
      - six [required: >=1.4.0, installed: 1.15.0]
      - traceback2 [required: Any, installed: 1.4.0]
        - linecache2 [required: Any, installed: 1.0.0]
      - unittest2 [required: >=1.0.0, installed: 1.1.0]
        - argparse [required: Any, installed: 1.1]
        - six [required: >=1.4, installed: 1.15.0]
        - traceback2 [required: Any, installed: 1.4.0]
          - linecache2 [required: Any, installed: 1.0.0]
  - funcsigs [required: Any, installed: 1.0.2]
  - idna [required: >=2.5,<2.8, installed: 2.7]
  - ipaddress [required: Any, installed: 1.0.23]
  - jsonschema [required: Any, installed: 3.2.0]
    - attrs [required: >=17.4.0, installed: 20.2.0]
    - importlib-metadata [required: Any, installed: 1.7.0]
      - zipp [required: >=0.5, installed: 3.1.0]
    - pyrsistent [required: >=0.14.0, installed: 0.17.3]
    - setuptools [required: Any, installed: 47.1.0]
    - six [required: >=1.11.0, installed: 1.15.0]
  - linecache2 [required: Any, installed: 1.0.0]
  - logger [required: Any, installed: 1.4]
  - Naked [required: Any, installed: 0.1.31]
    - pyyaml [required: Any, installed: 5.3.1]
    - requests [required: Any, installed: 2.24.0]
      - certifi [required: >=2017.4.17, installed: 2020.6.20]
      - chardet [required: >=3.0.2,<4, installed: 3.0.4]
      - idna [required: >=2.5,<3, installed: 2.7]
      - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
  - nose [required: Any, installed: 1.3.7]
  - paramiko [required: Any, installed: 2.7.2]
    - bcrypt [required: >=3.1.3, installed: 3.2.0]
      - cffi [required: >=1.1, installed: 1.14.2]
        - pycparser [required: Any, installed: 2.20]
      - six [required: >=1.4.1, installed: 1.15.0]
    - cryptography [required: >=2.5, installed: 3.1]
      - cffi [required: >=1.8,!=1.11.3, installed: 1.14.2]
        - pycparser [required: Any, installed: 2.20]
      - six [required: >=1.4.1, installed: 1.15.0]
    - pynacl [required: >=1.0.1, installed: 1.4.0]
      - cffi [required: >=1.4.1, installed: 1.14.2]
        - pycparser [required: Any, installed: 2.20]
      - six [required: Any, installed: 1.15.0]
  - pbr [required: Any, installed: 5.5.0]
  - pip [required: Any, installed: 20.1.1]
  - pyasn1 [required: Any, installed: 0.4.8]
  - pycparser [required: Any, installed: 2.20]
  - pycryptodome [required: Any, installed: 3.9.8]
  - pycryptodomex [required: Any, installed: 3.9.8]
  - PyJWT [required: Any, installed: 1.7.1]
  - PyNaCl [required: Any, installed: 1.4.0]
    - cffi [required: >=1.4.1, installed: 1.14.2]
      - pycparser [required: Any, installed: 2.20]
    - six [required: Any, installed: 1.15.0]
  - pyOpenSSL [required: Any, installed: 19.1.0]
    - cryptography [required: >=2.8, installed: 3.1]
      - cffi [required: >=1.8,!=1.11.3, installed: 1.14.2]
        - pycparser [required: Any, installed: 2.20]
      - six [required: >=1.4.1, installed: 1.15.0]
    - six [required: >=1.5.2, installed: 1.15.0]
  - pypi [required: Any, installed: 2.1]
  - python-mimeparse [required: Any, installed: 1.6.0]
  - python-subunit [required: Any, installed: 1.4.0]
    - extras [required: Any, installed: 1.0.0]
    - testtools [required: >=0.9.34, installed: 2.4.0]
      - extras [required: >=1.0.0, installed: 1.0.0]
      - fixtures [required: >=1.3.0, installed: 3.0.0]
        - pbr [required: >=0.11, installed: 5.5.0]
        - six [required: Any, installed: 1.15.0]
      - pbr [required: >=0.11, installed: 5.5.0]
      - python-mimeparse [required: Any, installed: 1.6.0]
      - six [required: >=1.4.0, installed: 1.15.0]
      - traceback2 [required: Any, installed: 1.4.0]
        - linecache2 [required: Any, installed: 1.0.0]
      - unittest2 [required: >=1.0.0, installed: 1.1.0]
        - argparse [required: Any, installed: 1.1]
        - six [required: >=1.4, installed: 1.15.0]
        - traceback2 [required: Any, installed: 1.4.0]
          - linecache2 [required: Any, installed: 1.0.0]
  - python-toolbox [required: Any, installed: 1.0.11]
    - setuptools [required: Any, installed: 47.1.0]
  - pytz [required: Any, installed: 2020.1]
  - PyYAML [required: Any, installed: 5.3.1]
  - requests [required: Any, installed: 2.24.0]
    - certifi [required: >=2017.4.17, installed: 2020.6.20]
    - chardet [required: >=3.0.2,<4, installed: 3.0.4]
    - idna [required: >=2.5,<3, installed: 2.7]
    - urllib3 [required: >=1.21.1,<1.26,!=1.25.1,!=1.25.0, installed: 1.25.10]
  - rsa [required: Any, installed: 4.6]
    - pyasn1 [required: >=0.1.3, installed: 0.4.8]
  - setuptools [required: Any, installed: 47.1.0]
  - shellescape [required: Any, installed: 3.8.1]
  - six [required: Any, installed: 1.15.0]
  - testtools [required: Any, installed: 2.4.0]
    - extras [required: >=1.0.0, installed: 1.0.0]
    - fixtures [required: >=1.3.0, installed: 3.0.0]
      - pbr [required: >=0.11, installed: 5.5.0]
      - six [required: Any, installed: 1.15.0]
    - pbr [required: >=0.11, installed: 5.5.0]
    - python-mimeparse [required: Any, installed: 1.6.0]
    - six [required: >=1.4.0, installed: 1.15.0]
    - traceback2 [required: Any, installed: 1.4.0]
      - linecache2 [required: Any, installed: 1.0.0]
    - unittest2 [required: >=1.0.0, installed: 1.1.0]
      - argparse [required: Any, installed: 1.1]
      - six [required: >=1.4, installed: 1.15.0]
      - traceback2 [required: Any, installed: 1.4.0]
        - linecache2 [required: Any, installed: 1.0.0]
  - traceback2 [required: Any, installed: 1.4.0]
    - linecache2 [required: Any, installed: 1.0.0]
  - typing [required: Any, installed: 3.7.4.3]
  - urllib3 [required: Any, installed: 1.25.10]
  - wheel [required: Any, installed: 0.35.1]
  - x509 [required: Any, installed: 0.1]
    - pyasn1 [required: >=0.1.7, installed: 0.4.8]
  - zope.interface [required: Any, installed: 5.1.0]
    - setuptools [required: Any, installed: 47.1.0]
```
