### ISSUE TITLE
ModuleNotFoundError: No module named 'CyberSource.logging'

### ISSUE THREAD

**Issue by maddenf** [CyberSource/cybersource-rest-samples-python#53]
Configuration has been setup.  Trying to run a sample PayerAuthentication script.

```
Traceback (most recent call last):
  File "samples/PayerAuthentication/authentication-with-new-account.py", line 7, in <module>
    configuration = SourceFileLoader("module.name", config_file).load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/foomanchu/projects/cybersource-rest-samples-python/data/Configuration.py", line 2, in <module>
    from CyberSource.logging.log_configuration import LogConfiguration
ModuleNotFoundError: No module named 'CyberSource.logging'
```

**Comment by francrubio** [comment]
Have you imported the Cybersource library?

from CyberSource import *
